-- Create Banks table
CREATE TABLE Banks (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(100) UNIQUE NOT NULL
);

-- Create Reviews table
CREATE TABLE Reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_text CLOB NOT NULL,
    rating NUMBER(2,1),
    review_date DATE,
    bank_id NUMBER REFERENCES Banks(bank_id),
    source VARCHAR2(50),
    sentiment_textblob_score NUMBER(5,4),
    sentiment_textblob_label VARCHAR2(20),
    compound_score NUMBER(5,4),
    sentiments_vader VARCHAR2(20),
    label VARCHAR2(20),
    predicted_sentiment VARCHAR2(20)
);